const category = [
  "camping",
  "hiking",
  "trail running",
  "skiing",
  "snowboarding",
  "surfing",
  "kayaking",
  "snorkeling",
  "skydiving",
  "rock climbing",
];

const skiResorts = [
  "49 Degrees North",
  "Afton Alps",
  "Alpine Meadows",
  "Alpine Mountain",
  "Alpine Valley",
  "Alpine Valley Resort",
  "Alta",
  "Alta Sierra",
  "Alyeska Resort",
  "Andes Tower Hills",
  "Angel Fire",
  "Antelope Butte",
  "Anthony Lakes",
  "Appalachian",
  "Apple Mountain",
  "Arapahoe Basin",
  "Arctic Valley",
  "Arizona Snowbowl",
  "Arrowhead",
  "Ascutney Mountain",
  "Aspen / Snowmass",
  "Aspen Highlands",
  "Aspen Mountain - Ajax",
  "Attitash",
  "Ausblick Ski Area",
  "Badger Mountain Ski Area",
  "Badger Pass",
  "Bald Mountain",
  "Balsams/Wilderness",
  "Bear Creek",
  "Bear Lodge Resort",
  "Bear Mountain",
  "Bear Mountain Valley Resort",
  "Bear Paw Ski Bowl",
  "Bear River Mountains (Naomi Peak)",
  "Bear Valley",
  "Bear's Den Mountain",
  "Bears Den",
  "Beartooth Pass",
  "Beaver Creek",
  "Beaver Mountain",
  "Beech Mountain Ski Resort",
  "Belleayre",
  "Berkshire East",
  "Big Air Green Valley Snowboard Park / Ski Green Valley",
  "Big Boulder",
  "Big Horn",
  "Big Mountain",
  "Big Powderhorn",
  "Big Rock Ski Area",
  "Big Squaw",
  "Bigrock",
  "Bittersweet",
  "Black Mountain",
  "Blackjack",
  "Blacktail Mountain",
  "Blandford",
  "Blue Hills",
  "Blue Knob",
  "Blue Marsh",
  "Blue Mountain",
  "Bluewood",
  "Bobcat Ski Center",
  "Bogus Basin",
  "Bolton Valley",
  "Boreal",
  "Boston Mills/Brandywine",
  "Bottineau Winter Park",
  "Bousquet",
  "Boyce Park",
  "Boyne Highlands",
  "Boyne Mountain",
  "Bradford",
  "Brantling Ski Slopes",
  "Brasstown Bald",
  "Breckenridge",
  "Bretton Woods",
  "Brian Head",
  "Bridger Bowl",
  "Brighton",
  "Bristol Mountain",
  "Bromley Mountain",
  "Bruce Mound Ski Area",
  "Brundage",
  "Bryce Resort",
  "Buck Hill",
  "Buckhorn Ski Club",
  "Buena Vista",
  "Buffalo Ski Club",
  "Burke Mountain",
  "Buttermilk",
  "Caberfae Peaks",
  "Camden Snow Bowl",
  "Camp 10",
  "Campgaw Mtn",
  "Campton",
  "Canaan Valley",
  "Cannon Mountains",
  "Cannonsburg",
  "Canyons Resort",
  "Cascade Mountain",
  "Cataloochee",
  "Catamount",
  "Cazenovia Ski Club",
  "Chester Ski Bowl",
  "Chestnut Mountain",
  "China Peak",
  "Chisos Mountains",
  "Christie Mountain",
  "Christmas Mountain",
  "Clear Fork",
  "Cloudmont",
  "Cochran Ski Area",
  "Cockaigne",
  "Coffee Mill",
  "Cooper Spur",
  "Copper Mountain",
  "Coppervale",
  "Cortina Mountain Resort",
  "Cranmore",
  "Crested Butte",
  "Crotched Mountain",
  "Crystal Ridge",
  "Cuchara Mountain",
  "Dartmouth Skiway",
  "Deer Mountain",
  "Deer Valley",
  "Detroit Mountain Ski Area",
  "Devil's Head",
  "Devil's Head Resort",
  "Diamond Lake Resort",
  "Diamond Peak",
  "Discovery",
  "Dodge Ridge",
  "Donner Ski Ranch",
  "Dry Hill",
  "Durango",
  "Eagle Point",
  "Eagle Rock",
  "Eaglecrest",
  "Eaton Mountain",
  "Echo Mountain Park",
  "Echo Valley Ski Area",
  "Eldora",
  "Elk Meadows",
  "Elk Mountain",
  "Elk Ridge",
  "Elko Snobowl Ski & Winter Recreation Area",
  "Elm Creek Park Reserve",
  "Enchanted Forest",
  "Estes Park",
  "Ferguson Ridge",
  "Four Lakes Village",
  "Four Seasons",
  "Frost Fire",
  "Fun Valley",
  "Giants Ridge",
  "Gladstone Sports Park",
  "Gore Mountain",
  "Gorgoza Park",
  "Grand Geneva Resort and Spa",
  "Grand Targhee",
  "Granite Gorge Ski Resort",
  "Granite Peak",
  "Granlibakken",
  "Great Bear",
  "Great Divide",
  "Greek Peak",
  "Gunstock",
  "Hanson Hills",
  "Hawksnest",
  "Haystack",
  "Heavenly",
  "Hermon Mountain",
  "Hesperus Ski Area",
  "Hickory Hills",
  "Hickory Ski Center",
  "Hidden Valley - MO",
  "Hidden Valley - NJ",
  "Hidden Valley - PA",
  "Highlands of Olympia",
  "Hilltop",
  "Hocking Hills",
  "Hogadon",
  "Holiday Mountain",
  "Holiday Valley",
  "HoliMont",
  "Homewood",
  "Hoodoo",
  "Howelsen",
  "Huff Hills",
  "Hunt Hollow",
  "Hunter Mountain",
  "Hurricane Ridge",
  "Hyland Ski & Snowboard",
  "Indianhead",
  "Jack Frost",
  "Jackson Hole",
  "Jay Peak",
  "Jiminy Peak",
  "June",
  "Kelly Canyon",
  "Kendall Mountain",
  "Kettlebowl",
  "Keystone",
  "Killington",
  "King Pine",
  "Kirkwood",
  "Kissing Bridge",
  "Labrador Mountain",
  "Las Vegas Ski",
  "Laurel Mountain",
  "Leavenworth Ski Resort",
  "Liberty Mountain",
  "Little Ski Hill Snow Resort",
  "Little Switzerland",
  "Lookout Pass",
  "Loon Mountain",
  "Lost Trail",
  "Lost Valley",
  "Loup Loup",
  "Loveland",
  "Lutsen Mountain",
  "Mad River",
  "Mad River Glen",
  "Magic Mountain Resort",
  "Mammoth",
  "Maple Ski Ridge",
  "Marquette",
  "Marshall Mountain",
  "Massanutten",
  "Mauna Kea",
  "Maverick",
  "McCauley",
  "McIntyre Ski Area",
  "Middlebury College Snow Bowl",
  "Missaukee Mountain",
  "Mission Ridge",
  "Mohawk Mountain",
  "Monarch",
  "Mont du Lac Ski Area",
  "Mont Dulac",
  "Mont Ripley",
  "Montage",
  "Montana Snowbowl",
  "Montecito Sequoia Resort",
  "Moonlight Basin",
  "Moose Mountain",
  "Mount Abram",
  "Mount Airy Lodge",
  "Mount Ashwabay Ski Area",
  "Mount Bohemia",
  "Mount Bohemia (Michigan)",
  "Mount Brighton",
  "Mount Eyak",
  "Mount Frontenac",
  "Mount Hood Meadows Ski Resort",
  "Mount Jefferson Ski Area",
  "Mount Katahdin",
  "Mount Kato",
  "Mount La Crosse",
  "Mount Marcy",
  "Mount Pleasant",
  "Mount Rainier",
  "Mount Shasta Ski Park",
  "Mount Snow",
  "Mount Sunapee",
  "Mount Tone",
  "Mountain Creek",
  "Mountain High",
  "Mountain High Resort",
  "Mountain Top at Grand Geneva",
  "Mountainview Ski Area",
  "Mt Abram",
  "Mt Ashland",
  "Mt Aurora Skiland",
  "Mt Bachelor",
  "Mt Bailey Snowcat Skiing",
  "Mt Baker",
  "Mt Baldy",
  "Mt Brighton",
  "Mt Crescent",
  "Mt Holiday",
  "Mt Holly",
  "Mt Hood Meadows",
  "Mt Hood Skibowl",
  "Mt Jefferson",
  "Mt LaCrosse",
  "Mt Lemmon Ski Valley",
  "Mt Peter",
  "Mt Rose",
  "Mt Shasta",
  "Mt Southington",
  "Mt Spokane",
  "Mt Zion",
  "Mt. Aurora Skiland Ski Area",
  "Mt. McSauba",
  "Mt. Waterman",
  "Mulligan's Hollow Ski Bowl",
  "Mystic Mountain",
  "Nashoba Valley",
  "New Hermon",
  "New Winterplace",
  "Nordic Mountain",
  "Nordic Valley",
  "Northstar at Tahoe",
  "Norway Mountain",
  "Nub's Nob Ski Area",
  "Nubs Nob",
  "Oak Mountain",
  "Ober Gatlinburg",
  "Oglebay Park Ski Area",
  "Okemo Mountain",
  "Otis Ridge",
  "Otsego",
  "Pajarito",
  "Pando Winter Sports Park",
  "Paoli Peaks",
  "Park City",
  "Pats Peak",
  "Pebble Creek",
  "Peek 'n Peak",
  "Peek'n Peak Resort",
  "Perfect North Slopes",
  "Pico",
  "Pico Mtn at Killington",
  "Pine Creek Ski Area",
  "Pine Knob",
  "Pine Mountain",
  "Pine Ridge Snow Park",
  "Pineridge Cross-Country",
  "Pines Peak",
  "Plattekill Mountain",
  "Plumas - Eureka Ski Bowl",
  "Pomerelle",
  "Porcupine Mountains",
  "Powder Mountain",
  "Powderhorn",
  "Quechee Lakes",
  "Ragged Mountain",
  "Raging Buffalo Snowboard Park",
  "Red Lodge",
  "Red River",
  "Riverside Hills",
  "Royal Gorge",
  "Royal Mountain",
  "Saddleback",
  "Sandia Peak",
  "Santa Fe Ski Area",
  "Sapphire Valley",
  "Sawkill Family Ski Center",
  "Sawtooth Mountains",
  "Schweitzer Mountain",
  "Scotch Valley Resort",
  "Seven Oaks",
  "Seven Springs",
  "Shanty Creek",
  "Shawnee Mountain",
  "Shawnee Peak",
  "Shirley Meadows",
  "Showdown",
  "Sierra at Tahoe",
  "Sierra Summit",
  "Silver Ridge",
  "Silverton Mountain",
  "Sipapu",
  "Sitzmark Lifts",
  "Ski Apache",
  "Ski Beech",
  "Ski Big Bear",
  "Ski Bradford",
  "Ski Brule",
  "Ski Brule / Ski Homestead",
  "Ski Butternut",
  "Ski Cloudcroft",
  "Ski Cooper",
  "Ski Denton",
  "Ski Green Valley",
  "Ski Gull Ski Area",
  "Ski Mystic Deer Mountain",
  "Ski Plattekill",
  "Ski Roundtop",
  "Ski Santa Fe",
  "Ski Sawmill",
  "Ski Snowstar",
  "Ski Sundown",
  "Ski Sunrise",
  "Ski Tamarack",
  "Ski Ward",
  "Sky Tavern",
  "Sky Valley",
  "Skyline",
  "Sleeping Giant",
  "Sleepy Hollow Sports Park",
  "Smugglers Notch",
  "Sno Mountain",
  "Snow Creek",
  "Snow Hill at Eastman",
  "Snow King",
  "Snow Ridge",
  "Snow Snake",
  "Snow Summit",
  "Snow Trails",
  "Snow Valley",
  "Snowbasin",
  "Snowbird",
  "Snowcrest at Kratka Ridge",
  "Snowhaven",
  "Snowmass",
  "Snowshoe Mountain",
  "Snowy Range",
  "Snowy Range Ski Area",
  "SnÃ¶ Mountain",
  "Soda Springs",
  "Soldier Mountain",
  "Solitude",
  "SolVista",
  "Song Mountain",
  "Spirit Mountain",
  "Split Rock Snow Ski Resort",
  "Spout Springs",
  "Spring Mountain",
  "Springer Mountain",
  "Squaw Valley USA",
  "Steamboat",
  "SteepleChase",
  "Sterling Forest",
  "Stevens Pass",
  "Storrs Hill",
  "Stover Mountain",
  "Stowe",
  "Stratton Mountain",
  "Sugar Bowl",
  "Sugar Loaf",
  "Sugar Mountain",
  "Sugarbush",
  "Sugarloaf/USA",
  "Suicide Six",
  "Summit Central at Snoqualmie",
  "Summit East at Snoqualmie",
  "Summit Ski Area",
  "Summit West at Snoqualmie",
  "Sun Valley",
  "Sunburst",
  "Sundance",
  "Sunday River",
  "Sundown Mountain",
  "Sunlight",
  "Sunrise Park",
  "Swain",
  "Swiss Valley",
  "Sylvan Hill Park",
  "Tahoe Donner",
  "Tamarack",
  "Tanglwood",
  "Taos",
  "Telemark",
  "Telluride",
  "Tenney Mountain",
  "Terry Peak",
  "Teton Pass",
  "The Balsams  Wilderness",
  "The Canyons",
  "The Granby Ranch",
  "The Homestead",
  "The Mount Washington Resort at Bretton Woods",
  "The Mountain Top at Grand Geneva Resort",
  "The Summit - at - Snoqualmie",
  "Thunder Ridge",
  "Timber Ridge",
  "Timberline Four Seasons",
  "Timberline Ski Resort",
  "Titcomb Mountain",
  "Titus Mountain",
  "Toggenburg",
  "Treetops",
  "Trollhaugen",
  "Turner Mountain",
  "Tussey Mountain",
  "Tuxedo Ridge at Sterling Forest",
  "Tyrol Basin",
  "Vail",
  "Villa Olivia",
  "Villa Roma",
  "Wachusett Mountain",
  "Warner Canyon",
  "Waterville Valley",
  "Welch Village",
  "West Mountain",
  "Whaleback Ski Area",
  "White Mountain Peak",
  "White Pass",
  "White Pine",
  "Whitecap Mountain",
  "Whiteface",
  "Whitefish",
  "Whitefish Mountain Resort",
  "Whitetail",
  "Wild Mountain",
  "Wildcat",
  "Wildcat Mountain",
  "Willamette Pass",
  "Willard Mountain",
  "Willowbrook Ski Area",
  "Wilmot Mountain",
  "Windham Mountain",
  "Windham Mtn",
  "Winter Park",
  "Winter Park Resort",
  "Wintergreen",
  "Winterplace",
  "Wisp",
  "Wolf Creek",
  "Wolf Creek Utah Resort",
  "Wolf Laurel",
  "Wolf Mountain",
  "Wolf Ridge Ski Resort",
  "Woodbury",
  "Woodbury Ski and Racquet Area",
  "Woodbury Ski Area",
  "Woods Valley",
  "Woods Valley Ski Area",
  "Yagoo Valley Ski Area",
  "Yawgoo Valley",
  "Yellowstone Club",
  "Yosemite's Badger Pass",
];

module.exports = { category, skiResorts };
